[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.build]
cmds = ["npm install", "npm run build"]

[phases.setup.env]
NODE_ENV = "production"

[start]
cmd = "npx serve -s dist -l ${PORT:-3000}"
