"""
Report export constants and enumerations.

Defines job types, export formats, status values, and template defaults
used across the export engine.
"""

import enum
from typing import Dict, Any

# ---------------------------------------------------------------------------
# Export Format Types
# ---------------------------------------------------------------------------

class ExportFormat(str, enum.Enum):
    """Supported export file formats."""

    PDF = "pdf"
    DOCX = "docx"
    XLSX = "xlsx"
    CSV = "csv"
    JSON = "json"


# ---------------------------------------------------------------------------
# Export Job Types
# ---------------------------------------------------------------------------

class ExportJobType(str, enum.Enum):
    """Categories of reports that can be exported."""

    ANALYTICS = "analytics"
    CAMPAIGN = "campaign"
    SOCIAL = "social"
    ERP = "erp"
    BILLING = "billing"
    FOLLOWERS = "followers"
    CUSTOM = "custom"


# ---------------------------------------------------------------------------
# Export Job Status Lifecycle
# ---------------------------------------------------------------------------

class ExportJobStatus(str, enum.Enum):
    """Lifecycle states for an export job."""

    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


# ---------------------------------------------------------------------------
# MIME Type Mapping
# ---------------------------------------------------------------------------

EXPORT_MIME_TYPES: Dict[str, str] = {
    ExportFormat.PDF: "application/pdf",
    ExportFormat.DOCX: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ExportFormat.XLSX: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ExportFormat.CSV: "text/csv",
    ExportFormat.JSON: "application/json",
}

# ---------------------------------------------------------------------------
# File Extension Mapping
# ---------------------------------------------------------------------------

EXPORT_EXTENSIONS: Dict[str, str] = {
    ExportFormat.PDF: ".pdf",
    ExportFormat.DOCX: ".docx",
    ExportFormat.XLSX: ".xlsx",
    ExportFormat.CSV: ".csv",
    ExportFormat.JSON: ".json",
}

# ---------------------------------------------------------------------------
# Default Template Configuration
# ---------------------------------------------------------------------------

DEFAULT_TEMPLATE_CONFIG: Dict[str, Any] = {
    "primary_color": "#2563EB",
    "secondary_color": "#1E40AF",
    "accent_color": "#3B82F6",
    "text_color": "#1F2937",
    "light_bg": "#F3F4F6",
    "white": "#FFFFFF",
    "font_family": "Helvetica",
    "header_font_size": 10,
    "body_font_size": 9,
    "title_font_size": 18,
    "subtitle_font_size": 12,
    "page_size": "A4",
    "orientation": "portrait",
    "margin_top": 72,
    "margin_bottom": 72,
    "margin_left": 72,
    "margin_right": 72,
    "logo_width": 120,
    "logo_height": 40,
    "footer_text": "Generated by Report Engine",
    "header_line": True,
    "footer_line": True,
    "show_page_numbers": True,
    "show_generated_at": True,
    "watermark_text": None,
}

# ---------------------------------------------------------------------------
# Status Display Labels (for UI)
# ---------------------------------------------------------------------------

STATUS_LABELS: Dict[str, str] = {
    ExportJobStatus.PENDING: "Pending",
    ExportJobStatus.PROCESSING: "Processing",
    ExportJobStatus.COMPLETED: "Completed",
    ExportJobStatus.FAILED: "Failed",
    ExportJobStatus.CANCELLED: "Cancelled",
}

FORMAT_LABELS: Dict[str, str] = {
    ExportFormat.PDF: "PDF Document",
    ExportFormat.DOCX: "Word Document",
    ExportFormat.XLSX: "Excel Spreadsheet",
    ExportFormat.CSV: "CSV File",
    ExportFormat.JSON: "JSON File",
}

JOB_TYPE_LABELS: Dict[str, str] = {
    ExportJobType.ANALYTICS: "Analytics Report",
    ExportJobType.CAMPAIGN: "Campaign Report",
    ExportJobType.SOCIAL: "Social Media Report",
    ExportJobType.ERP: "ERP Report",
    ExportJobType.BILLING: "Billing Report",
    ExportJobType.FOLLOWERS: "Followers Report",
    ExportJobType.CUSTOM: "Custom Report",
}

# ---------------------------------------------------------------------------
# Signed URL Configuration
# ---------------------------------------------------------------------------

SIGNED_URL_EXPIRY_SECONDS = 3600  # 1 hour
SIGNED_URL_ALGORITHM = "HS256"

# ---------------------------------------------------------------------------
# Export File Storage
# ---------------------------------------------------------------------------

EXPORT_STORAGE_DIR = "exports"
MAX_EXPORT_FILE_SIZE_MB = 50
EXPORT_CLEANUP_DAYS = 7

# Aliases for service layer
EXPORT_FORMATS_LABEL = FORMAT_LABELS
EXPORT_JOB_TYPES_LABEL = JOB_TYPE_LABELS
