"""
Pydantic schemas for report export API.

Defines request/response models for export job CRUD, signed URL
responses, and template configuration validation.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.reports.constants import (
    ExportFormat,
    ExportJobStatus,
    ExportJobType,
    FORMAT_LABELS,
    JOB_TYPE_LABELS,
    STATUS_LABELS,
)


# ---------------------------------------------------------------------------
# Template Config Schema
# ---------------------------------------------------------------------------

class TemplateConfigSchema(BaseModel):
    """Company-branded report template configuration."""

    model_config = ConfigDict(extra="allow")

    primary_color: Optional[str] = Field(default="#2563EB", pattern=r"^#[0-9A-Fa-f]{6}$")
    secondary_color: Optional[str] = Field(default="#1E40AF", pattern=r"^#[0-9A-Fa-f]{6}$")
    accent_color: Optional[str] = Field(default="#3B82F6", pattern=r"^#[0-9A-Fa-f]{6}$")
    text_color: Optional[str] = Field(default="#1F2937", pattern=r"^#[0-9A-Fa-f]{6}$")
    light_bg: Optional[str] = Field(default="#F3F4F6", pattern=r"^#[0-9A-Fa-f]{6}$")
    white: Optional[str] = Field(default="#FFFFFF", pattern=r"^#[0-9A-Fa-f]{6}$")
    font_family: Optional[str] = "Helvetica"
    header_font_size: Optional[int] = Field(default=10, ge=6, le=24)
    body_font_size: Optional[int] = Field(default=9, ge=6, le=24)
    title_font_size: Optional[int] = Field(default=18, ge=10, le=48)
    subtitle_font_size: Optional[int] = Field(default=12, ge=8, le=32)
    page_size: Optional[str] = Field(default="A4", pattern=r"^(A4|Letter|Legal)$")
    orientation: Optional[str] = Field(default="portrait", pattern=r"^(portrait|landscape)$")
    logo_width: Optional[int] = Field(default=120, ge=20, le=400)
    logo_height: Optional[int] = Field(default=40, ge=10, le=200)
    footer_text: Optional[str] = "Generated by Report Engine"
    header_line: Optional[bool] = True
    footer_line: Optional[bool] = True
    show_page_numbers: Optional[bool] = True
    show_generated_at: Optional[bool] = True
    watermark_text: Optional[str] = None


# ---------------------------------------------------------------------------
# Create Export Job Request
# ---------------------------------------------------------------------------

class ExportJobCreateRequest(BaseModel):
    """Request body to create a new async export job."""

    model_config = ConfigDict(use_enum_values=True)

    job_type: str = Field(
        ...,
        description="Type of report to export",
        examples=["analytics", "campaign", "social", "erp"],
    )
    format: str = Field(
        ...,
        description="Export file format",
        examples=["pdf", "docx", "xlsx", "csv", "json"],
    )
    report_title: Optional[str] = Field(
        default=None,
        max_length=255,
        description="Custom report title",
    )
    report_params: Optional[Dict[str, Any]] = Field(
        default_factory=dict,
        description="Report query parameters (filters, date ranges, etc.)",
    )
    template_config: Optional[TemplateConfigSchema] = None
    branch_id: Optional[int] = None

    @field_validator("format")
    @classmethod
    def validate_format(cls, v: str) -> str:
        allowed = {f.value for f in ExportFormat}
        if v not in allowed:
            raise ValueError(f"format must be one of: {allowed}")
        return v

    @field_validator("job_type")
    @classmethod
    def validate_job_type(cls, v: str) -> str:
        allowed = {t.value for t in ExportJobType}
        if v not in allowed:
            raise ValueError(f"job_type must be one of: {allowed}")
        return v


# ---------------------------------------------------------------------------
# Export Job Response
# ---------------------------------------------------------------------------

class ExportJobResponse(BaseModel):
    """Export job detail response."""

    model_config = ConfigDict(from_attributes=True)

    id: int
    company_id: int
    branch_id: Optional[int]
    job_type: str
    format: str
    status: str
    file_path: Optional[str]
    file_size: Optional[int]
    file_size_human: Optional[str]
    file_name: Optional[str]
    error_message: Optional[str]
    retry_count: int
    max_retries: int
    report_title: Optional[str]
    report_params: Optional[Dict[str, Any]]
    template_config: Optional[Dict[str, Any]]
    created_by: Optional[int]
    created_at: datetime
    started_at: Optional[datetime]
    completed_at: Optional[datetime]
    duration_seconds: Optional[float]

    # Computed labels
    status_label: str = ""
    format_label: str = ""
    job_type_label: str = ""


class ExportJobListResponse(BaseModel):
    """Paginated list of export jobs."""

    items: List[ExportJobResponse]
    total: int
    page: int
    page_size: int


class ExportJobStatusResponse(BaseModel):
    """Minimal status response for polling."""

    id: int
    status: str
    status_label: str
    progress_percent: Optional[int] = None
    file_size_human: Optional[str]
    error_message: Optional[str]
    completed_at: Optional[datetime]


# ---------------------------------------------------------------------------
# Signed Download URL
# ---------------------------------------------------------------------------

class SignedDownloadUrlResponse(BaseModel):
    """Pre-signed download URL response."""

    download_url: str
    expires_at: datetime
    file_name: str
    file_size_human: Optional[str]
    mime_type: str


# ---------------------------------------------------------------------------
# Export Filter Parameters
# ---------------------------------------------------------------------------

class ExportJobFilterParams(BaseModel):
    """Query parameters for listing export jobs."""

    status: Optional[str] = None
    job_type: Optional[str] = None
    format: Optional[str] = None
    branch_id: Optional[int] = None
    page: int = Field(default=1, ge=1)
    page_size: int = Field(default=20, ge=1, le=100)
    sort_by: str = Field(default="created_at", pattern=r"^(created_at|completed_at|status)$")
    sort_order: str = Field(default="desc", pattern=r"^(asc|desc)$")


# ---------------------------------------------------------------------------
# Template Preview
# ---------------------------------------------------------------------------

class TemplatePreviewResponse(BaseModel):
    """Template configuration preview response."""

    primary_color: str
    secondary_color: str
    font_family: str
    page_size: str
    orientation: str
    logo_available: bool
    sample_header: str
    sample_footer: str
