"""
Report template engine for company-branded reports.

Manages company logo paths, color schemes, font configurations,
and template defaults for consistent branding across all export formats.
"""

import os
from typing import Any, Dict, Optional

from app.reports.constants import DEFAULT_TEMPLATE_CONFIG


class ReportTemplateEngine:
    """
    Company-branded report template manager.

    Loads company-specific branding (logo, colors, fonts) and merges
    with defaults to produce a complete template configuration for
    all export engines (PDF, DOCX, XLSX, CSV, JSON).
    """

    # Logo storage base path
    LOGO_BASE_DIR = "/app/storage/logos"

    def __init__(
        self,
        company_id: int,
        company_name: Optional[str] = None,
        logo_filename: Optional[str] = None,
        custom_colors: Optional[Dict[str, str]] = None,
        custom_config: Optional[Dict[str, Any]] = None,
    ):
        self.company_id = company_id
        self.company_name = company_name or f"Company {company_id}"
        self.logo_filename = logo_filename
        self.custom_colors = custom_colors or {}
        self.custom_config = custom_config or {}

    def build_config(self) -> Dict[str, Any]:
        """
        Build the complete template configuration.

        Merges: defaults < company colors < company custom config.

        Returns:
            Dict with all template settings.
        """
        config = DEFAULT_TEMPLATE_CONFIG.copy()

        # Apply company colors
        color_map = {
            "primary_color": self.custom_colors.get("primary"),
            "secondary_color": self.custom_colors.get("secondary"),
            "accent_color": self.custom_colors.get("accent"),
            "text_color": self.custom_colors.get("text"),
            "light_bg": self.custom_colors.get("light_bg"),
        }
        for key, value in color_map.items():
            if value:
                config[key] = value

        # Apply custom overrides
        config.update(self.custom_config)

        # Override footer text with company name
        config["footer_text"] = f"Generated by {self.company_name} Report Engine"

        return config

    def get_logo_path(self) -> Optional[str]:
        """
        Resolve the full logo file path if it exists.

        Returns:
            Absolute path to logo file, or None if not available.
        """
        if not self.logo_filename:
            return None

        logo_path = os.path.join(self.LOGO_BASE_DIR, str(self.company_id), self.logo_filename)
        if os.path.exists(logo_path):
            return logo_path

        # Try fallback paths
        fallback_paths = [
            os.path.join(self.LOGO_BASE_DIR, self.logo_filename),
            f"/app/storage/company_{self.company_id}_logo.png",
            f"/app/storage/company_{self.company_id}_logo.jpg",
        ]
        for path in fallback_paths:
            if os.path.exists(path):
                return path

        return None

    @classmethod
    def from_company_record(cls, company: Any) -> "ReportTemplateEngine":
        """
        Create template engine from a Company ORM record.

        Expects company to have attributes:
            - id: int
            - name: str
            - logo_url or logo: str (optional)
            - brand_colors: dict (optional, JSON column)
            - report_config: dict (optional, JSON column)
        """
        logo = None
        if hasattr(company, "logo_url") and company.logo_url:
            logo = os.path.basename(company.logo_url)
        elif hasattr(company, "logo") and company.logo:
            logo = os.path.basename(company.logo)

        brand_colors = {}
        if hasattr(company, "brand_colors") and company.brand_colors:
            brand_colors = company.brand_colors

        custom_config = {}
        if hasattr(company, "report_config") and company.report_config:
            custom_config = company.report_config

        return cls(
            company_id=company.id,
            company_name=company.name if hasattr(company, "name") else None,
            logo_filename=logo,
            custom_colors=brand_colors if isinstance(brand_colors, dict) else {},
            custom_config=custom_config if isinstance(custom_config, dict) else {},
        )

    @classmethod
    async def from_company_id(
        cls,
        db_session: Any,
        company_id: int,
    ) -> "ReportTemplateEngine":
        """
        Async factory: load company from DB and build template engine.

        Args:
            db_session: SQLAlchemy async session.
            company_id: Company ID.

        Returns:
            Configured ReportTemplateEngine.
        """
        from sqlalchemy import select

        # Lazy import to avoid circular dependency
        result = await db_session.execute(
            select(__import__("app.companies.models", fromlist=["Company"]).Company).where(
                __import__("app.companies.models", fromlist=["Company"]).Company.id == company_id
            )
        )
        company = result.scalar_one_or_none()

        if company is None:
            return cls(company_id=company_id)

        return cls.from_company_record(company)
